version: 2

jobs:
  build:
    docker:
      - image: rust:1.27.1

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Stable Build
          command: |
            rustc --version --verbose
            cargo --version --verbose
            cargo build
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
